# Generated by Django 2.2.7 on 2019-11-19 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='billtype',
            table='bookkeeping_bill_type',
        ),
    ]
