version: "3"
services:
  redis:
    image: redis:5.0
    command: redis-server
    volumes:
      - ./deployment/redis/data:/data
    ports:
      - "6378:6379"
    restart: always

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=duole_mini
      - MYSQL_ROOT_PASSWORD=DxqWVXH2
    volumes:
      - ./deployment/mysql/data:/var/lib/mysql
      - ./deployment/mysql/my.cnf:/etc/mysql/my.cnf
    ports:
      - "3305:3306"
    restart: always

  py_api:
    build: .
    ports:
      - "9090:9090"
    volumes:
      - .:/duole_mini
    command: bash start.sh
    links:
      - mysql
      - redis
    restart: always
    stdin_open: true
    tty: true

  nginx:
    build: deployment/nginx
    ports:
      - "8000:80"
      - "442:443"
    links:
      - py_api
    depends_on:
      - py_api
    restart: always
    stdin_open: true
    tty: true